/*
 * This source file was generated by the Gradle 'init' task
 */
package numer0n;

import numer0n.constant.GameConfig;
import numer0n.factory.service.GameManagerFactory;
import numer0n.service.GameManager;

public class App {

    public static void main(String[] args) {
        // ゲームを開始
        GameManager manager=GameManagerFactory.create();
        manager.start();
    }
}
